name:
  Publish to Google Play Store

on:
  push:
    branches:
      - release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish_to_play_store:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Write property file
        uses: GuillaumeFalourd/write-java-properties-file@v1
        with:
          file_path: 'local.properties'
          property: |
            oauth.url
            service.url
          value: |
            ${{ secrets.OAUTH_URL }}
            ${{ secrets.SERVICE_URL }}

      - name: Generate build number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Create short SHA
        run: echo "SHA_SHORT=`echo ${GITHUB_SHA} | cut -c1-5`" >> $GITHUB_ENV

      - name: Create release name
        run: echo "RELEASE_NAME=$(date "+%y%m%d").${{ steps.buildnumber.outputs.build_number }}" >> $GITHUB_ENV

      - name: Create version name
        run: echo "VERSION_NAME=${{ env.RELEASE_NAME }} (${{ env.SHA_SHORT }})" >> $GITHUB_ENV

      - name: Apply version properties to build.gradle
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: androidApp/build.gradle.kts
          versionCode: ${{ steps.buildnumber.outputs.build_number }}
          versionName: ${{ env.VERSION_NAME }}

      - name: Build bundle
        run: ./gradlew androidApp:bundleRelease

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: net.schacher.mcc
          releaseFiles: androidApp/build/outputs/bundle/release/androidApp-release.aab
          track: internal

      - name: Create tag
        run: |
          git config --global user.name "github-action"
          git config --global user.email "github-actions@schacher.pro"
          git tag -a "${{ env.RELEASE_NAME }}" -m "Created release tag"
          git push origin --tags

      - name: Build changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v2.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.RELEASE_NAME }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          files: |
            androidApp/build/outputs/bundle/release/androidApp-release.aab
